### ISSUE TITLE
:return-list ?

### ISSUE THREAD

**Issue by leblowl** [igrishaev/mockery#6]
Hey thanks for writing this. It is pretty cool to see how simply one can implement mocking. I was considering using alexanderjamesking/spy but I'm not sure what I would gain from that library over this one. Anyways, I see you have `:call-args-list` but I don't see any `:return-list`, just the latest return value `:return`. I think `:return-list`  (lists all past return values) could be helpful for batch assertions.

**Comment by igrishaev** [comment]
Thank you @leblowl , will take a look once I'm back from a journey.

**Comment by igrishaev** [comment]
@leblowl it's done, see the tests/readme. Please bump the version to `[mockery "0.1.3"]`

**Comment by leblowl** [comment]
Thanks!
